# Permalinks
permalink:              /:categories/:title/
relative_permalinks:    true

# Setup
title:                  edX Pattern Library
tagline:                The Visual, UI, and Front End Styleguide for edX
url:                    http://code.edx.org/ux-pattern-library
author:
    name:                 edX UX
    url:                  http://www.edx.org
    email:                ux@edx.org

# Custom vars
github:
    repo:                 https://github.com/edx/ux-pattern-library

# Site/View Config
baseurl:                /

# Plugins
highlighter:            pygments;

